name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL5LIB: ${HOME}/perl5/lib/perl5
  PERL_LOCAL_LIB_ROOT: ${HOME}/perl5
  PERL_MB_OPT: --install_base ${HOME}/perl5
  PERL_MM_OPT: INSTALL_BASE=${HOME}/perl5

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
          #- '5.8'
          #- '5.10'
          #- '5.16'
          - 'latest'
          #- 'threaded'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Probe wd
        run: |
          pwd
          ls -l

      #- name: Install pkgconfig
      #  run: apt-get install pkgconfig
        
      - name: Install Gtk etc
        run: |
          apt-get update
          apt-get --yes --force-yes install libcairo2-dev libpango1.0-dev libgtk2.0-dev libproj-dev

      - name: perl -V
        run: |
          which perl
          echo $PATH
          perl -V

      - name: Prepare for cache
        run: |
          perl -V > perlversion.txt
          #  change the checksum so we refresh the cache
          echo 'with shared Alien installs' >> perlversion.txt
          ls -l perlversion.txt

      #- name: clear cache
      #  run: rm ~/perl5/${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Cache CPAN modules
        uses: actions/cache@v1
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Install cpan deps 
        run: |
          cpanm --notest ExtUtils::PkgConfig
          cpanm --notest ExtUtils::Depends
          cpanm --notest Gtk2
          cpanm --notest PAR::Packer
          cpanm --notest File::BaseDir
          cpanm --notest File::Find::Rule
          cpanm --notest File::Which
          cpanm --notest Capture::Tiny
          cpanm --notest List::Util
          cpanm --notest File::Find::Rule
          cpanm --notest Path::Tiny
          cpanm --notest File::Temp
          cpanm --notest Module::ScanDeps
          cpanm --notest Env
      
      
      - name: Test pack
        run: |
          echo Running perl dynamic_libs check
          #  do we pack libproj
          #find /usr/local -name libproj.so -print
          #  dpkg -L libproj-dev | grep libproj
          #export libproj=`find /usr/local -name libproj.so -print`
          #echo LIBPROJ is at $libproj
          perl bin/pp_autolink.pl -o checkpp tester.pl
          #perl bin/pp_autolink.pl --link $libproj -o checkpp tester.pl
          echo Running checkpp dynamic libs check
          ./checkpp
          echo Running checkpp with /usr/local dirs out of the way
          sudo mv /usr/local/opt /usr/local/optx
          sudo mv /usr/local/Cellar /usr/local/Cellarx
          ./checkpp
          echo Putting /usr/local dirs back
          sudo mv /usr/local/optx /usr/local/opt
          sudo mv /usr/local/Cellarx /usr/local/Cellar
          echo Dylib files in packed archive:
          unzip -l checkpp | grep dylib
        
      - name: Upload checkpp artefact
        uses: actions/upload-artifact@v1
        with:
          name: checkpp
          #path: ${DMG_FILE_NAME}
          path: ./checkpp
